In [ ]:
1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [1]:
class Employee:
    total_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.total_employees += 1

    def average_salary(self, employee_list):
        total_salary = 0
        for e in employee_list:
            total_salary += e.salary
        return total_salary / len(employee_list)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

# Creating instances of Employee and FulltimeEmployee classes
employee1 = Employee("John Doe", "Family A", 60000, "HR")
employee2 = Employee("Jane Smith", "Family B", 55000, "IT")
fulltime_employee1 = FulltimeEmployee("Alice Johnson", "Family C", 70000, "Finance")

# Calling member functions
employees = [employee1, employee2, fulltime_employee1]
avg_salary = employee1.average_salary(employees)
print(f"Average salary: ${avg_salary:.2f}")
print(f"Total employees: {Employee.total_employees}")

Average salary: $61666.67
Total employees: 3


In [ ]:
2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [2]:
import numpy as np


random_vector = np.random.uniform(1, 20, size=20)

print("original vector : ",random_vector)

reshaped_array = random_vector.reshape(4, 5)


reshaped_array[np.arange(reshaped_array.shape[0]), np.argmax(reshaped_array, axis=1)] = 0

print("Original reshaped array:")
print(reshaped_array)

original vector :  [12.24770334  5.68016086 16.84576277  3.84752509  4.80283023 17.14074919
 14.92945107 15.10218988  3.90311395  4.08942718 16.86064639 11.02634371
  9.23371671 12.90602173  6.03089328 17.28168941  2.29418961 19.66984433
 19.12159907 15.43529976]
Original reshaped array:
[[12.24770334  5.68016086  0.          3.84752509  4.80283023]
 [ 0.         14.92945107 15.10218988  3.90311395  4.08942718]
 [ 0.         11.02634371  9.23371671 12.90602173  6.03089328]
 [17.28168941  2.29418961  0.         19.12159907 15.43529976]]
